image:
  # image.parentRepository -- Docker registry to pull images from
  parentRepository: gcr.io/jenkinsxio

  # image.tag -- Docker images tag
  tag: 0.0.120

  # image.pullPolicy -- Image pull policy
  pullPolicy: IfNotPresent

gcJobs:
  # gcJobs.schedule -- Cron expression to periodically garbage collect `Preview` resources; every 10 minutes by default
  schedule: "*/10 * * * *"

  # gcJobs.failedJobsHistoryLimit -- Drives the failed jobs history limit
  failedJobsHistoryLimit: 1

  # gcJobs.successfulJobsHistoryLimit -- Drives the successful jobs history limit
  successfulJobsHistoryLimit: 3

  # gcJobs.concurrencyPolicy -- Drives the job's concurrency policy
  concurrencyPolicy: Forbid

  image:
    # gcJobs.image.repository -- Template for computing the gc job docker image repository
    repository: "{{ .Values.image.parentRepository }}/jx-cli"

    # gcJobs.image.tag -- Template for computing the gc job docker image tag
    tag: "latest"

    # gcJobs.image.pullPolicy -- Template for computing the gc job docker image pull policy
    pullPolicy: "{{ .Values.image.pullPolicy }}"


