{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-05-11T12:36:07Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    branch: master
    committer:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    message: |
      fix: avoid storing git credentials in the preview custom resource

      this helps avoid stale tokens being used to clone the repo when a preview is being garbage collected, instead user or in cluster git credentials are used by default
    sha: b23de50d89bb7f94f155f191a35d425b2f494323
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: |-
      fix: upgrade the boot image

      so we get the same helmfile version as used in jx-preview
    sha: 36d3520386c3441028603c125b839aed5c7fd8fb
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: upgrade deps
    sha: 6140d7014f39bdabfada9cbd20041a002b1d7212
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: added JSON schema generation
    sha: 99839eb735d02361f137c226a61a566de7c69766
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-preview
  gitOwner: jenkins-x-plugins
  gitRepository: jx-preview
  name: '{{ .Chart.Name }}'
  version: 0.0.182
status: {}
 
{{- end }}
