{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-18T05:53:28Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: wowq@users.noreply.github.com
      name: wowq
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: Update values.yaml
    sha: ef8ab029f2bb94791eac9d5f895c6aafa604a53d
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      fix: value error
    sha: a63e7f9097cd3be9b1ff54d6b8bcda4589c30848
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      fix: support other git provider
    sha: 61bd3f92e0081a28aeab69ceb06509ccf9e81ed9
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-preview
  gitOwner: jenkins-x-plugins
  gitRepository: jx-preview
  name: '{{ .Chart.Name }}'
  version: 0.0.180
status: {}
 
{{- end }}
