{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-06-25T16:01:03Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: regen docs
    sha: b25d1710994ecc69aca108cd64f735d0c33e4d74
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: add command to template a preview

      so its easier to debug what happens in a preview
    sha: 9def3dc8e100152f54b08134c70fc344254ddbb8
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: ugprade deps
    sha: a92983762d90d39fc7d7e79fbd0203f956b4c362
  - author:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    branch: master
    committer:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    message: |
      fix: avoid storing git credentials in the preview custom resource

      this helps avoid stale tokens being used to clone the repo when a preview is being garbage collected, instead user or in cluster git credentials are used by default
    sha: b23de50d89bb7f94f155f191a35d425b2f494323
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-preview
  gitOwner: jenkins-x-plugins
  gitRepository: jx-preview
  name: '{{ .Chart.Name }}'
  version: 0.0.183
status: {}
 
{{- end }}
