{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-26T06:34:06Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: upgrade deps
    sha: bff7fc592345bac3daa8189baf44882c1056d1d9
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix pipeline
    sha: 0cac6efe7a6fdea022ff06a285aa135aad667445
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: upgrade deps
    sha: a5dd9d4a312f2e7691c31dacf3ed1a09bafa12b7
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: the docker registry
    sha: 7171ca394b22b348c7d48904a6cda1a4af7a3f3f
  gitHttpUrl: https://github.com/jenkins-x/jx-preview
  gitOwner: jenkins-x
  gitRepository: jx-preview
  name: '{{ .Chart.Name }}'
  version: 0.0.172
status: {}
 
{{- end }}
